# Generated by Django 3.0.6 on 2020-06-04 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='Student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoolmanagement.Student'),
        ),
    ]
