# Generated by Django 3.0.6 on 2020-06-04 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmanagement', '0002_subject_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoolmanagement.Class'),
        ),
    ]
