# Generated by Django 3.0.6 on 2020-06-04 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmanagement', '0005_student_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='Student',
        ),
        migrations.AddField(
            model_name='teacher',
            name='Subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoolmanagement.Subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='Subject1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='Subject2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='Subject3',
            field=models.CharField(max_length=100),
        ),
    ]
