# Generated by Django 3.0.6 on 2020-06-04 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmanagement', '0006_auto_20200604_0640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='Subject2',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='Subject3',
        ),
    ]
