# Generated by Django 3.0.6 on 2020-06-04 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmanagement', '0007_auto_20200604_0644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='Subject1',
            new_name='Subject',
        ),
    ]
