# Generated by Django 3.0.6 on 2020-06-04 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmanagement', '0008_auto_20200604_0651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='School',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Class',
        ),
        migrations.RemoveField(
            model_name='student',
            name='School',
        ),
        migrations.AddField(
            model_name='class',
            name='Student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoolmanagement.Student'),
        ),
    ]
