# Generated by Django 3.0.6 on 2020-06-04 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmanagement', '0011_auto_20200604_0758'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Students',
        ),
    ]
