# Generated by Django 3.0.6 on 2020-06-04 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmanagement', '0012_auto_20200604_0808'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Studentss',
        ),
    ]
