# Generated by Django 3.0.6 on 2020-06-04 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmanagement', '0013_auto_20200604_1039'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Studentss',
            new_name='Students',
        ),
    ]
