# Generated by Django 3.0.6 on 2020-06-04 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmanagement', '0015_studentslist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='Student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoolmanagement.Studentslist'),
        ),
    ]
