# Generated by Django 3.0.6 on 2020-06-04 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmanagement', '0016_auto_20200604_1047'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students',
        ),
        migrations.RemoveField(
            model_name='class',
            name='Student',
        ),
        migrations.AddField(
            model_name='class',
            name='Students',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoolmanagement.StudentsList'),
        ),
    ]
