# Generated by Django 3.0.6 on 2020-06-04 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmanagement', '0022_auto_20200604_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Students',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoolmanagement.StudentsList'),
        ),
        migrations.AlterField(
            model_name='class',
            name='StudentsList',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoolmanagement.StudentsList'),
        ),
    ]
