# Generated by Django 3.0.6 on 2020-06-04 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmanagement', '0023_auto_20200604_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='StudentsList',
            new_name='Student',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='Students',
        ),
        migrations.AlterField(
            model_name='class',
            name='Student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoolmanagement.StudentsList'),
        ),
    ]
