# Generated by Django 3.0.6 on 2020-06-05 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmanagement', '0028_auto_20200605_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentslist',
            options={},
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='Subject',
        ),
        migrations.AlterField(
            model_name='class',
            name='Student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoolmanagement.StudentsList'),
        ),
    ]
