# Generated by Django 3.0.6 on 2020-06-05 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmanagement', '0029_auto_20200605_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoolmanagement.Subject'),
        ),
        migrations.AlterField(
            model_name='class',
            name='Student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoolmanagement.StudentsList'),
        ),
    ]
